### ISSUE TITLE
kill does not work anymore with latest releases (0.7.5, 0.7.6)

### ISSUE THREAD

**Issue by jupe** [Microsoft/node-pty#206]
## Environment details

- OS: linux/eg rasbian
- OS version: all I think
- node-pty version: 0.7.5, 0.7.6

## Issue description
`ptyProcess.kill()` does not have affect anymore.

Reproducing easily by spawning `sleep 10` :
```
var pty = require('node-pty');
var ptyProcess = pty.spawn('sleep', [10], {});
ptyProcess.on('exit', (exitcode, signal) => {
  console.log(exitcode, signal);
});
ptyProcess.kill('SIGKILL')
```

Above script kill directly when using node-pty@v0.7.4, but latest releases waits until sleep is done unexpectedly.

**Comment by jupe** [comment]
Probably this PR causes issue: https://github.com/Microsoft/node-pty/pull/169/files
Especially this line: https://github.com/Microsoft/node-pty/pull/169/files#diff-0e9d5f27e04ca315ef8d403ff86bf5dfR241 . If I hack that part a bit so that `process.kill` is called every time above script seems to work again.

**Comment by Tyriar** [comment]
Thoughts @Daniel-Abrecht @jerch?

**Comment by Daniel-Abrecht** [comment]
After analyzing the problem further, it turned out that the ioctl returned an EINVAL error. After looking at the linux kernel sources, I figured out that linux only allows this ioctl for SIGINT, SIGQUIT and SIGTSTP: https://github.com/torvalds/linux/blob/master/drivers/tty/pty.c#L211

I've only ever tried sending SIGINT or SIGQUIT, so I never noticed this problem before. I'll start working on a patch to check if pty.kill throws an error and call process.kill in that case tomorrow evening, it's already really late in my timezone. Sorry for the inconvenience.

**Comment by jupe** [comment]
Thank you Daniel for investigating this. Let me know as soon as patch is available so I could try out it also.

**Comment by Tyriar** [comment]
@jerch like this?

```ts
kill(signal?: string, sendToProcessGroup?: boolean): void;
```

Seems reasonable.

**Comment by Daniel-Abrecht** [comment]
I've created a pull request. Please test if everything works again. Someone also needs to try if the windows version still compiles, since I don't have a windows pc to try that.

**Comment by jupe** [comment]
Fix seems to help, thanks @Daniel-Abrecht. @Tyriar can we get this in patch release soon ?

**Comment by jupe** [comment]
Any news when we get release ?

**Comment by Tyriar** [comment]
@jupe chatting with legal about CLA issues, I recommend sticking with 0.7.4 in the meantime.

**Comment by Tyriar** [comment]
I reverted the offending change https://github.com/Microsoft/node-pty/commit/7360eb70b16a9e0b122a33844be58769db21010a
