### ISSUE TITLE
Unexpectedly clears the screen on Windows

### ISSUE THREAD

**Issue by lydell** [microsoft/node-pty#423]
## Environment details

- OS: Windows 10 Home
- OS version: 10.0.18363
- node-pty version: 0.9.0

## Issue description

Code to reproduce:

```js
const pty = require("node-pty");
const terminal = pty.spawn("cmd.exe", '/d /s /c "echo test"', {});
terminal.onData((data) => process.stdout.write(JSON.stringify(data)));
terminal.onExit(() => process.exit());
```

Output:

```
"\u001b[2J\u001b[?25l\u001b[m\u001b[H\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\u001b[H\u001b]0;C:\\Windows\\SYSTEM32\\cmd.exe\u0007\u001b[?25h""\u001b[?25ltest\r\n\u001b[?25h"
```

Expected:

```
"test"
```

The ANSI escapes and newlines seem to clear the screen (remove `JSON.stringify` to try it out). I don’t want the screen to be cleared. If I run `cmd.exe /d /s /c "echo test"` in cmd.exe the screen is _not_ cleared (it looks like only `test\n` is printed).

Is this a bug somewhere? Or am I misunderstanding something?

**Comment by lydell** [comment]
Thanks, conptyInheritCursor does seem to get rid of the unexpected clearing. :+1:

**Comment by Mr-Wallet** [comment]
I'm still getting this with `conptyInheritCursor`, it just happens sooner:

I had an issue where immediately after PowerShell writes its preamble and then I write my own preamble to the terminal, the screen was clearing before showing the PowerShell prompt.

After adding `conptyInheritCursor`, the clear screen was pushed back so that my own preamble survives, but it's still happening, so it still nukes the default PowerShell preamble.

What is causing it to spit out a whole screen's worth of `ESC [K` at startup? Is there any way to prevent it?

**Comment by mofux** [comment]
Only a guess, but maybe the PTY is getting resized in between? I'd check if `pty.resize(...)` is getting called.

**Comment by Mr-Wallet** [comment]
Possible, but if that's the case why would _this_ resize clear it and not other ones later which I know are happening? 🤔

**Comment by mofux** [comment]
Hard to tell. Maybe initialize the pty with a fixed size in frontend (without using `xterm-addon-fit`) and backend. Make sure you are not sending any resizes. Then check if you are still seeing those sequences. If you do then it's probably caused by something else... 🤔

**Comment by Mr-Wallet** [comment]
I didn't have much time to investigate but I though I should record my findings before the weekend so that I don't forget:

I've determined that it's caused by calling `resize` on the pty process. Normally it will re-draw the entire screen in order to try and make the resize work out okay (I don't know the details, but this has persistently been a very difficult point with conpty). The question is why it's completely dropping all initial output from the shell when it does a resize right away. It seems like if I wait "long enough" then the buffer is "safe" and resizing no longer causes problems from then on. 🤷

**Comment by Mr-Wallet** [comment]
After a day of investigation, I think this is probably my team and I mis-using XTerm (at least while using PowerShell. Resizing is... interesting with CMD). Basically we are medding with XTerm too much and I think it was getting "out of sync" with pty, and screen redraws (i.e. resizes) were "fixing" that disparity. Problem Exists Between Keyboard and Chair!
