### ISSUE TITLE
node-pty is causing problems on ARM Systems beacuase glibc_2.28 dependency

### ISSUE THREAD

**Issue by Misery42** [microsoft/node-pty#428]
## Environment details

OS and Version: Remote System is running
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
- node-pty version: 0.10.0-beta17

## Issue description
https://github.com/microsoft/vscode-cpptools/issues/6116

**Comment by Tyriar** [comment]
@joaomoreno any ideas on what needs to happen here?

**Comment by sean-mcmanus** [comment]
FYI, our C/C++ extension for ARM builds on Ubuntu 18 core (with Ubuntu 16 packages), which allows us to have a glibc 2.17 dependency instead of the 2.28 one that would occur by building on Ubuntu 20 or Debian 10. It's possible the build machine got updated to a new OS and took the higher 2.28 dependency.

Since Ubuntu 18 and Debian 9 only support 2.27, and usage of Ubuntu 18 and Debian 9 are still significant, the 2.28 dependency is too high (see https://github.com/microsoft/vscode-cpptools/issues/5993 ).

Our goal was to meet the 2.27 glibc dependency and drop Ubuntu 16, Debian 8, and CentOS 7, which had low usage, but we got support for those older OS's "for free" due to the usage of the Ubuntu 16 packages.

**Comment by Misery42** [comment]
Using VS Code 1.49.0 solves the problem for me so far.

my newest os build has:

sudo dpkg -l | grep libc6
ii  libc6:armhf                           2.24-11+deb9u4                    armhf        GNU C Library: Shared libraries
ii  libc6-dbg:armhf                       2.24-11+deb9u4                    armhf        GNU C Library: detached debugging symbols
ii  libc6-dev:armhf                       2.24-11+deb9u4                    armhf        GNU C Library: Development Libraries and Header Files

**Comment by sean-mcmanus** [comment]
Our telemetry indicates that 46% of our ARM users would be impacted by this VS Code 1.50.0-insiders regression, so they would be stuck on VS Code 1.49.0 until they upgraded their OS.

**Comment by Tyriar** [comment]
@deepak1556 is this related to the Electron update?

**Comment by deepak1556** [comment]
Not related to electron update, this comes from @joaomoreno recent work for arm https://github.com/microsoft/vscode/pull/106289 , the build container was updated to use debian buster which uses glibc 2.28

**Comment by cheesefinger** [comment]
+1 having the same problem.

**Comment by Tyriar** [comment]
@deepak1556 our regular build container for all of VS Code? Won't that break support for Ubuntu 14/16/18 too?

**Comment by joaomoreno** [comment]
Yeah I definitely changed the base docker images for the ARM server bits and decided to go with Debian buster. I am in the process to switch back to stretch, tomorrow's builds should already go back to the previous glibc version. Will update it here.
