### ISSUE TITLE
No loader is configured for ".node" files (vite & tauri)

### ISSUE THREAD

**Issue by AviAvinav** [microsoft/node-pty#566]
## Environment details

- OS: Windows
- OS version: 11
- node-pty version: 0.10.1

## Issue description

I am trying to use node-pty with vite (react) and [tauri](https://tauri.app/). I have been running into the following error:

```
X [ERROR] No loader is configured for ".node" files: node_modules/node-pty/build/Release/pty.node
```

Is there a way I can fix this, I looked into a similar issue and found a solution for vue: https://github.com/microsoft/node-pty/issues/435#issuecomment-715502116, how can I do this in vite?

**Comment by daniel-brenot** [comment]
The issue here is that you are trying to load a native module from a browser context. This isn't possible, and i believe using this in the context of tauri isn't quite the way to go. I suggest using rust code to do this using some available libraries since you are using tauri. Alternatively you may be able to sideload node.js, and if so you could use this library from that context.

**Comment by Tyriar** [comment]
Also I'll add that this is generally discouraged in Electron as well as sandboxed renderers are better for both security and performance.
